FROM node:lts-slim AS clarify-ui

ARG WA_PAGE_VIEW_HIT
ARG UI_APP_CONFIG
ARG CLIENT_PLUGINS
ARG DISABLE_SOURCE_MAPS
ARG SOURCE_MAPS_TOKEN

ENV TERM=xterm \
    LANG='C.UTF-8'  \
    LC_ALL='C.UTF-8'

# Install dependencies
COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY clarify-core/package.json /tmp/clarify-core/
COPY clarify-canvas/package.json /tmp/clarify-canvas/
COPY clarify-canvas3d/package.json /tmp/clarify-canvas3d/
COPY clarify-ui/package.json /tmp/clarify-ui/
COPY clarify-data/package.json /tmp/clarify-data/

# Install common dependencies
WORKDIR /tmp/
RUN DISABLE_HUSKY=1 yarn --frozen-lockfile

# Build source code
COPY clarify-data/ /tmp/clarify-data/
COPY clarify-core/ /tmp/clarify-core/
COPY clarify-canvas3d/ /tmp/clarify-canvas3d/
COPY clarify-canvas/ /tmp/clarify-canvas/
COPY clarify-ui/ /tmp/clarify-ui/
RUN CLIENT_PLUGINS="${CLIENT_PLUGINS}" \
DISABLE_SOURCE_MAPS="${DISABLE_SOURCE_MAPS}" \
UI_APP_CONFIG="${UI_APP_CONFIG}" \
SOURCE_MAPS_TOKEN="${SOURCE_MAPS_TOKEN}" yarn run build:clarify-ui

FROM nginx:mainline-alpine
# Replace default.conf configuration to remove unnecessary rules
COPY clarify-ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=clarify-ui /tmp/clarify-ui/dist /usr/share/nginx/html/
