
# This optional Docker Compose file may be used to deploy CLARIFY with an external database.

x-backend-settings: &backend-settings
  environment:
    CLARIFY_POSTGRES_HOST:
    CLARIFY_POSTGRES_PORT:
    CLARIFY_POSTGRES_DBNAME:
    CLARIFY_POSTGRES_USER:
    CLARIFY_POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  secrets:
    - postgres_password

services:
  clarify_db:
    deploy:
      replicas: 0

  clarify_server: *backend-settings
  clarify_utils: *backend-settings
  clarify_worker_analytics_reports: *backend-settings
  clarify_worker_annotation: *backend-settings
  clarify_worker_export: *backend-settings
  clarify_worker_import: *backend-settings
  clarify_worker_quality_reports: *backend-settings
  clarify_worker_webhooks: *backend-settings

secrets:
  postgres_password:
    environment: CVAT_POSTGRES_PASSWORD