
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.clarify.opa.composeCompatibleServiceName }}
  name: opa
  {{- else }}
  name: {{ .Release.Name }}-opa-service
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clarify.labels" . | nindent 4 }}
    app: clarify-app
    tier: opa
spec:
  selector:
    app: clarify-app
    tier: opa
    {{- include "clarify.labels" . | nindent 4 }}
  {{- with .Values.clarify.opa.service }}
  {{- toYaml . | nindent 2 }}
  {{- end }}