{{- if .Values.clarify.kvrocks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kvrocks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clarify.labels" . | nindent 4 }}
    app: clarify-app
    tier: kvrocks
spec:
  selector:
    app: clarify-app
    tier: kvrocks
    {{- include "clarify.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: 6666
    targetPort: 6666
    protocol: TCP
    name: http
{{- end }}