{{- $localValues := .Values.clarify.backend.worker.webhooks -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-worker-webhooks
  namespace: {{ .Release.Namespace }}
  labels:
    app: clarify-app
    tier: backend
    component: worker-webhooks
    {{- include "clarify.labels" . | nindent 4 }}
    {{- with merge $localValues.labels .Values.clarify.backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge $localValues.annotations .Values.clarify.backend.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $localValues.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "clarify.labels" . | nindent 6 }}
      {{- with merge $localValues.labels .Values.clarify.backend.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      app: clarify-app
      tier: backend
      component: worker-webhooks
  template:
    metadata:
      labels:
        app: clarify-app
        tier: backend
        component: worker-webhooks
        {{- include "clarify.labels" . | nindent 8 }}
        {{- with merge $localValues.labels .Values.clarify.backend.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with merge $localValues.annotations .Values.clarify.backend.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: clarify-backend
          image: {{ .Values.clarify.backend.image }}:{{ .Values.clarify.backend.tag }}
          imagePullPolicy: {{ .Values.clarify.backend.imagePullPolicy }}
          {{- with merge $localValues.resources .Values.clarify.backend.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["run", "worker.webhooks"]
          env:
          {{ include "clarify.sharedBackendEnv" . | indent 10 }}
          {{- with concat .Values.clarify.backend.additionalEnv $localValues.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with concat .Values.clarify.backend.additionalVolumeMounts $localValues.additionalVolumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with merge $localValues.affinity .Values.clarify.backend.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat .Values.clarify.backend.tolerations $localValues.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat .Values.clarify.backend.additionalVolumes $localValues.additionalVolumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}