{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  # vector helm doesn't allow template name of CM
  name: clarify-analytics-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clarify.labels" . | nindent 4 }}
    app: clarify-app
    tier: analytics
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
immutable: true
{{- end }}
stringData:
  CLICKHOUSE_DB: {{ .Values.analytics.clickhouseDb }}
  CLICKHOUSE_USER: {{ .Values.analytics.clickhouseUser }}
  CLICKHOUSE_PASSWORD: {{ .Values.analytics.clickhousePassword }}
  CLICKHOUSE_HOST: {{ tpl (.Values.analytics.clickhouseHost) . }}
{{- end }}